apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubia.fullname" . }}
  labels:
    {{- include "kubia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubia.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: luksa/kubia:{{ .Values.imageTag | default "v1" }}
